version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_TIMEZONE: 'America/Santiago'
    container_name: db-needvox
    volumes:
      - ./postgres:/var/lib/postgresql/data